language: php

php:
  - 5.6
  - 7.0
  - hhvm

branches:
  except:
    - /^((release|hotfix)\/)?\d\.\d/
    - /^(feature|bugfix)\//

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml.dist --coverage-text
